### PR TITLE
Remove SCard struct names and extra braces from logs

### PR DESCRIPTION
**Pull request by emaxx-google**
Stop printing structure names in PC/SC logs, in cases where the
type is already clear from the context. Also remove some unneeded
extra braces.

Example of changes:
* BEFORE: SCardListReaders: returning 0x00000000 ["Command successful."], mszReaders=MultiString["Foo 00 00"]
* AFTER: SCardListReaders: returning 0x00000000 ["Command successful."], mszReaders=["Foo 00 00"]
* BEFORE: SCardGetStatusChange(hContext=0x595DF1EC, dwTimeout=60000, rgReaderStates=0xFEB403D8([SCARD_READERSTATE(szReader="Foo 00 00", pvUserData=0x00000001, dwCurrentState=SCARD_STATE_CHANGED|SCARD_STATE_PRESENT|SCARD_STATE_INUSE)]))
* AFTER: SCardGetStatusChange(hContext=0x595DF1EC, dwTimeout=60000, rgReaderStates=0xFEB403D8[{szReader="Foo 00 00", pvUserData=0x00000001, dwCurrentState=SCARD_STATE_CHANGED|SCARD_STATE_PRESENT|SCARD_STATE_INUSE}])

This change contributes to the logging improvements tracked
by #146.

### CODE REVIEW

**Comment by emaxx-google** [comment]
Let me actually rework this into a bigger change that removes similar verbosity in other parts of the file.

**Comment by emaxx-google** [comment]
> Let me actually rework this into a bigger change that removes similar verbosity in other parts of the file.

Done

**Review by Fabian-Sommer — APPROVED** [review]
LGTM

**Review by ayaNader — APPROVED** [review]
LGTM

**Pull request merged**
