### PR TITLE
Add Xtralogic RDP Client to the list of known client apps

### PR DESCRIPTION
**Pull request by xtralogic**
Add Xtralogic RDP Client, stable and beta editions, to the list of known client apps

### CODE REVIEW

**Comment by xtralogic** [comment]
I've signed the CLA, please verify!

**Comment by emaxx-google** [comment]
Sorry, something didn't go well with the CLA. The bot should've replied here with something like "CLAs look good", and the "cla/google" check here shouldn't be displayed as "failing".
@xtralogic, could you please double-check the steps necessary for the CLA?

**Comment by xtralogic** [comment]
I've submitted pull request before I've signed the CLA, so the bot check failed. Later I've signed the CLA and when I click the "Check your existing CLA data" link above it shows the individual agreement is on file. Is it possible to re-run the bot?

**Comment by emaxx-google** [comment]
No idea what was wrong, but now everything seems alright. Thanks.
Just curious - doesn't "fdlpibjfnlhnmeckjjhfiejfdghkmkdm" need to be included as well? Or that one is a non Chrome OS specific version?

**Comment by xtralogic** [comment]
Yes, the 'fdlpibjfnlhnmeckjjhfiejfdghkmkdm' definitely needs to be included, it's a production channel edition.

**Comment by xtralogic** [comment]
Would it be possible to make a release which would include the changes in this pull request? We'd like to avoid the scary permission dialog to be shown to the customers.

**Comment by emaxx-google** [comment]
Sorry for the delay. The release 1.2.15.0, which includes this change, has just been published.

**Pull request merged**
